Adding deploy logic and dispatch workflow for terraform stack deploy

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -118,4 +118,64 @@ jobs:
           name: terraform-plan
           path: ${{ github.workspace }}/${{ inputs.stack }}/plan/*
           if-no-files-found: error
+  approval:
+    name: 'Manual Approval for Terraform - ${{ inputs.stack }} - ${{ inputs.environment }}'
+    runs-on: ubuntu-latest
+    needs: test
+    if: ${{ github.event_name == 'workflow_dispatch' && inputs.action != 'plan' }}
+    steps:
+      - name: Manual Approval
+        uses: trstringer/manual-approval@v1
+        with:
+          secret: ${{ github.TOKEN }}
+          approvers: ${{ github.actor}}
+          issue-title: 'Terraform Approval for ${{ inputs.stack }} - ${{ inputs.environment }}'
+          issue-body: |
+            Please review the Terraform plan and approve or reject the changes.
+            - Stack: ${{ inputs.stack }}
+            - Environment: ${{ inputs.environment }}
+            - Action: ${{ inputs.action }}
+  run:
+    name: 'Run Terraform - ${{ inputs.stack }} - ${{ inputs.environment }} - ${{ inputs.action }}'
+    runs-on: ubuntu-latest
+    needs: approval
+    if: ${{ inputs.action != 'plan' && github.event_name != 'workflow_dispatch' }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: latest
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ inputs.aws_region }}
+          role-to-assume: ${{ inputs.role }}
+          role-session-name: GitHubActionsSession
+
+      - name: Init
+        run: |
+          mkdir plan
+          account_id=$(aws account get-account-information --query AccountId --output text)
+          state_bucket="${{ inputs.state_bucket_prefix }}-$account_id-${{ inputs.aws_region }}"
+          terraform init \
+            -input=false \
+            --backend-config="bucket=$state_bucket" \
+            --backend-config="key=${{ inputs.stack }}/terraform.tfstate" \
+            --backend-config="region=${{ inputs.aws_region }}"
+
+      - name: Workspace
+        run: terraform workspace select ${{ inputs.environment }}
       
+      - name: Download Terraform Plan Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: terraform-plan
+          path: ${{ github.workspace }}/${{ inputs.stack }}/plan
+
+      - name: Run Terraform Action
+        run: |
+          terraform ${{ inputs.action }} plan/tfplan -auto-approve -input=false || echo "::warning file=terraform-${{ inputs.stack}}::Terraform ${{ inputs.action }} failed"
