Adding Terraform setup steps

diff --git a/.github/workflows/terraform-setup.yaml b/.github/workflows/terraform-setup.yaml
--- a/.github/workflows/terraform-setup.yaml
+++ b/.github/workflows/terraform-setup.yaml
@@ -58,10 +58,26 @@ jobs:
           aws-region: eu-west-2
           role-to-assume: ${{ inputs.role }}
           role-session-name: GitHubActionsSession
-      - name: Initialise Terraform
+      - name: Init
         run: |
           account_id=$(aws account get-account-information --query AccountId --output text)
           state_bucket="${{ inputs.state_bucket_prefix }}-$account_id-${{ inputs.aws_region }}"
           terraform init -input=false -backend-config="bucket=$state_bucket" --backend-config="key=${{ inputs.stack }}/terraform.tfstate" --backend-config="region=${{ inputs.aws_region }}"
-      - name: Check Format
+      - name: Workspace
+        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
+      - name: Format
         run: terraform fmt -check --recursive || echo "::warning file=terraform-aws::Terraform format check failed"
+      - name: Validate
+        run: terraform validate || echo "::warning file=terraform-aws::Terraform validation failed"
+      - name: Plan
+        run: |
+          mkdir plan
+          terraform plan -out=plan/tfplan -input=false || echo "::warning file=terraform-aws::Terraform plan failed"
+          terraform show -json tfplan > plan/plan.json
+      - name: Upload Plan
+        uses: actions/upload-artifact@v3
+        with:
+          name: terraform-plan
+          path: plan/*
+          if-no-files-found: error
+      
