Feature/add tests (#3)
- Restructured workflow designs
- Added TFlint static code linting
- Added Checkov scanning against TFPlan
= Added test results publishing

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -1,4 +1,4 @@
-name: Terraform Template
+name: Terraform
 
 on:
   workflow_call:
@@ -34,42 +34,84 @@ on:
 
 jobs:
   test:
-    name: 'Test AWS Terraform Code'
+    name: 'Terraform Plan and Test - ${{ inputs.stack }} - ${{ inputs.environment }}'
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
     defaults:
       run:
-        shell: bash
         working-directory: ${{ github.workspace }}/${{ inputs.stack }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: latest
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-region: eu-west-2
           role-to-assume: ${{ inputs.role }}
           role-session-name: GitHubActionsSession
+
       - name: Init
         run: |
           account_id=$(aws account get-account-information --query AccountId --output text)
           state_bucket="${{ inputs.state_bucket_prefix }}-$account_id-${{ inputs.aws_region }}"
-          terraform init -input=false -backend-config="bucket=$state_bucket" --backend-config="key=${{ inputs.stack }}/terraform.tfstate" --backend-config="region=${{ inputs.aws_region }}"
+          terraform init \
+            -input=false \
+            --backend-config="bucket=$state_bucket" \
+            --backend-config="key=${{ inputs.stack }}/terraform.tfstate" \
+            --backend-config="region=${{ inputs.aws_region }}"
+
       - name: Workspace
         run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
+
       - name: Format
         run: terraform fmt -check --recursive || echo "::warning file=terraform-aws::Terraform format check failed"
+
       - name: Validate
         run: terraform validate || echo "::warning file=terraform-aws::Terraform validation failed"
+
       - name: Plan
         run: |
-          mkdir plan
-          terraform plan -out=plan/tfplan -input=false || echo "::warning file=terraform-aws::Terraform plan failed"
+          mkdir plan tests
+          terraform plan \
+            -out=plan/tfplan \
+            -input=false \
+            --var-file=environments/${{ inputs.environment }}.tfvars || echo "::warning file=terraform-aws::Terraform plan failed"
           terraform show -json plan/tfplan > plan/plan.json
+
+      - name: Setup TFLint
+        uses: terraform-linters/setup-tflint@v4
+        with:
+          tflint_version: latest
+
+      - name: Run TFLint
+        run: |
+          config_file="${{ github.workspace }}/.github/workflows/resources/.tflint.hcl"
+          tflint --init --config "$config_file"
+          tflint \
+            --var-file=environments/${{ inputs.environment }}.tfvars \
+            --config "$config_file" \
+            --format junit > tests/tflint.xml || echo "::warning file=terraform-aws::TFLint failed"
+
+      - name: Install and run Checkov
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          file: ${{ github.workspace }}/${{ inputs.stack }}/plan/plan.json
+          output_format: junitxml
+          output_file_path: ${{ github.workspace }}/${{ inputs.stack }}/tests/
+
+      - name: Publish Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        with:
+          files: |
+            ${{ github.workspace }}/${{ inputs.stack }}/tests/results_junitxml.xml
+            ${{ github.workspace }}/${{ inputs.stack }}/tests/tflint.xml
+
       - name: Upload Plan
         uses: actions/upload-artifact@v4
         with:
